@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml


LAYOUT_TOP_DOWN()

Person(pco, "Pessoa Cliente da Ong", "Um cliente da Ong.")

System(sdi, "Sistema de Dispositivo Móvel", "Permite ao usuário visualizar e doar PETs, realizar denuncias e doações para o cuidado dos animais.")
System(swb, "Sistema WEB", "Permite ao usuário visualizar e doar PETs, realizar denuncias e doações para o cuidado dos animais.")
System(sys, "Sistema da ANIMAPET", "Posibilita aos usuários realizarem doações, denuncias, pedidos de doação e cadastros.")
System_Ext(ems, "Sistema de E-mail", "Sistema de envio e recebimento de e-mail.")
System_Ext(spo, "Sistema de Denuncia", "Sistema de denuncia de maus tratos aos animais")
System_Ext(pix, "Sistema de Pagamentos", "Sistema de envio e recebimento de pagamentos")


Rel(pco, sdi, "Usa")
Rel(pco, swb, "Usa")
Rel(sdi, sys, "Acessa","API")
Rel(swb, sys, "Acessa","API")
Rel(ems, pco, "Envia e-mails para")
Rel(sys, ems, "Envia e-mails", "SMTP")
Rel(sys, spo, "Usa","API")
Rel(sys, pix, "Usa","API")



@enduml