@startuml ContextoMacro
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml

LAYOUT_TOP_DOWN()

Person(cliente, "Pessoa Cliente da Ong", "Um cliente da Ong.")

System(mobile, "Sistema de Dispositivo Móvel", "Permite ao usuário visualizar e doar PETs, realizar denuncias e doações para o cuidado dos animais.")
System(web, "Sistema WEB", "Permite ao usuário visualizar e doar PETs, realizar denuncias e doações para o cuidado dos animais.")
System(sistema, "Sistema da ANIMAPET", "Posibilita aos usuários realizarem doações, denuncias, pedidos de doação e cadastros.")
System_Ext(email, "Sistema de E-mail", "Sistema de envio e recebimento de e-mail.")
System_Ext(financeiro, "Sistema de Denuncia", "Sistema de denuncia de maus tratos aos animais")
System_Ext(denuncia, "Sistema de Pagamentos", "Sistema de envio e recebimento de pagamentos")


Rel(cliente, mobile, "Usa")
Rel(cliente, web, "Usa")
Rel(mobile, sistema, "Acessa","API")
Rel(web, sistema, "Acessa","API")
Rel(email, cliente, "Envia e-mails para")
Rel(sistema, email, "Envia e-mails", "SMTP")
Rel(sistema, financeiro, "Usa","API")
Rel(sistema, denuncia, "Usa","API")

@enduml