@startuml ComponenteSPA
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Component.puml

LAYOUT_WITH_LEGEND()

Container(api, "API Application", "java e Spring MVC", "Fornece as funcionalidades do sistema Animapet via uma API JSON/HTTPS.")

Container_Boundary(spa, "Single Page Application") {
    Component(login, "Formulário de Login", "React Functional Component", "Formulário onde o usuario faz o login")
    Component(adocao, "Tela de Anúncios", "React Functional Component", "A tela onde são listados os animais para adoção")
    Component(criacao, "Tela de Criação de Anúncios", "React Functional Component", "A tela onde os anúncios de adoção são criados")
    Component(detalhes, "Tela de Detalhes de Anúncios", "React Functional Component", "A tela onde é possível visualizar detalhes de um anúncio específico")
    Component(chat, "Tela de Chat", "React Functional Component", "A tela onde o anunciante e o adotante podem conversar")
    Component(routing, "Routing", "React Router", "Gerencia o roteamento no lado do cliente")
}

Rel(spa, api, "Usa", "JSON/HTTPS")

Rel(login, routing, "Usa");
Rel(adocao, routing, "Usa");
Rel(criacao, routing, "Usa");
Rel(detalhes, routing, "Usa");
Rel(chat, routing, "Usa");

@enduml
