@startuml ContextoMacro
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Context.puml


LAYOUT_WITH_LEGEND()

Person(pco, "Pessoa", "Cliente da Ong.")

System(sys, "Sistema da ANIMAPET", "Posibilita aos usuários acessar o sistema e realizarem doações, denuncias, pedidos de doação e cadastros.")

System_Ext(ems, "Sistema de E-mail", "Sistema de envio e recebimento de e-mail.")
System_Ext(spo, "Sistema de Denuncia", "Sistema de denuncia de maus tratos aos animais")
System_Ext(pix, "Sistema de Pagamentos", "Sistema de envio e recebimento de pagamentos")

Rel(pco, sys, "Usa")
Rel(sys, ems, "Envia e-mails", "SMTP")
Rel(ems, pco, "Envia e-mails para")
Rel(sys, spo, "Usa","API")
Rel(sys, pix, "Usa","API")



@enduml